### PR TITLE
 jwm-2.3.7-1-x86_64, numlockx-1.2-1-x86_64

### PR DESCRIPTION
**Pull request by simargl**

### CODE REVIEW

**Comment by abucodonosor** [comment]
Hi @simargl

we don't use github for PR, however is a good place to review.

I pushed your ffmped hunk since I was about to update ffmpeg today.
The other 2 packages got removed from the repos some time ago because
no maintainer for these ( and some others ) so not sure whatever we want
to add them back.

**Comment by simargl** [comment]
Ok, thank you @abucodonosor
here's one more suggestion, now that ffmpeg is compiled with networking support, 
For mpv package would be nice to include 'luajit2' dependency and 
--enable-lua option in ./waf configure, so it can play youtube videos.

**Comment by abucodonosor** [comment]
@simargl 

I'll investigate mpv ..

Btw .. just open bug reports / feature request for packages you think
we are missing the one or the other feature..

Or just join #frugalware.dev channel on freenode and poke there :)

**Comment by abucodonosor** [comment]
Done..

..
commit ffba5f705bd4b401e9a07c4c0a1cfb05f6b2531b
Author: crazy <crazy@frugalware.org>
Date:   Fri Jul 27 16:53:11 2018 +0200

    mpv-0.27.2-3-x86_64
    
    * enabled lua , reqested on github by @simargl
...

**Comment by abucodonosor** [comment]
I may re-add the other 2 packages .. need to find some time on weekend to have a look

**Comment by simargl** [comment]
Thank you!

**Pull request closed without merging**
